#!/usr/bin/env python3
"""Generate prototype.html from the five screen files.

The five files are the source of truth. This script inlines usarr.css and
usarr.js, concatenates the five <main> blocks, and rewrites every link to the
five files into a #hash route so the single file clicks through the same way.
"""
import re, pathlib

SRC = pathlib.Path(__file__).resolve().parent
PAGES = [('home', 'index.html'), ('services', 'services.html'),
         ('libraries', 'libraries.html'), ('search', 'search.html'),
         ('requests', 'requests.html')]
ROUTE = {'index.html': '#home', 'services.html': '#services',
         'libraries.html': '#libraries', 'search.html': '#search',
         'requests.html': '#requests'}


def block(text, name):
    m = re.search(r'<!-- ' + name + r' START -->(.*?)<!-- ' + name + r' END -->', text, re.S)
    if not m:
        raise SystemExit('marker not found: ' + name)
    return m.group(1)


def rewrite_links(html):
    # Filenames may carry a #fragment or a ?query (the media-type nav entries
    # are search.html?type=..., the library scope is ?lib=..., and the
    # Search-to-Requests action is requests.html?q=...&type=...).
    #
    # The query is carried across rather than dropped. It used to be thrown
    # away, which made every media-type nav entry collapse onto a bare #search
    # and -- once Search grew a "Search indexers" action per row -- would have
    # silently discarded the query and category the whole action exists to
    # pass. usarr.js's router splits the hash on "?" so the route still
    # resolves, and the parameters survive in the address bar where a reader
    # can see that they are real.
    def sub(m):
        route = ROUTE[m.group('file')]
        query = m.group('query') or ''
        # A #fragment on a cross-page link cannot survive hash routing; a
        # ?query can, so only the query is kept.
        if query.startswith('#'):
            query = ''
        return 'href="' + route + query + '"'

    pattern = (r'href="(?P<file>' + '|'.join(re.escape(f) for f in ROUTE) +
               r')(?P<query>[?#][^"]*)?"')
    return re.sub(pattern, sub, html)


# fonts.css carries the two @font-face rules and nothing else, so usarr.css
# stays a stylesheet a person can read. Both are inlined here, fonts first,
# because prototype.html has to be a single file with no external request.
css = (SRC / 'fonts.css').read_text() + '\n' + (SRC / 'usarr.css').read_text()
js = (SRC / 'usarr.js').read_text()
index = (SRC / 'index.html').read_text()

sprite = block(index, 'SPRITE')
topbar = rewrite_links(block(index, 'TOPBAR'))

# This file is the one built for publishing, so the statement that it is a
# mockup over invented data has to survive a regenerate. It lives in the shared
# top bar rather than on any one page, and this assertion is what stops a
# future edit to index.html quietly dropping it from every screen at once.
if 'class="mocknote"' not in topbar:
    raise SystemExit('the permanent mockup notice is missing from the top bar')
sidebar = rewrite_links(block(index, 'SIDEBAR')).replace(' aria-current="page"', '')

body = '\n'.join(rewrite_links(block((SRC / f).read_text(), 'PAGE:' + r).strip())
                 for r, f in PAGES)

# The <title> is user-visible copy -- it is the browser tab, the bookmark and
# the history entry -- so §13's rules bind it like any other string, and
# check.mjs now reads document.title for exactly that reason. It used to say
# "UsArr v0.1 screen mockup — static, invented data, nothing implemented",
# which broke both: an em dash in a nine-word string, and a v0.1 claim over a
# page whose default view is the full stack, which §16 sequences AFTER v0.1.
# The milestone belongs to the install switcher, which can state it truthfully
# for whichever install is selected; a fixed title cannot.
#
# It then read "UsArr screen mockups: static, invented data, nothing
# implemented" until the screens shipped and "nothing implemented" went false —
# the same defect as the top-bar notice, in the one string a rendered DOM walk
# cannot see. What survives is the half that stays true: the data is invented.
# Implementation status is §16's and the tree's, not a browser tab's, and
# check.mjs asserts that document.title claims none (REVIEW-LOG SD-01a).
out = f'''<!doctype html>
<html lang="en" data-density="compact">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>UsArr screen mockups: static, invented data</title>
<style>
{css}
</style>
</head>
<body>
<!-- Generated from index.html, services.html, libraries.html, search.html and
     requests.html. Do not edit this file by hand: edit those five and
     regenerate with build_prototype.py. -->
{sprite}
<div class="app" data-sidebar="open">
{topbar}
{sidebar}
{body}
</div>
<div class="toasts"></div>
<script>
{js}
</script>
</body>
</html>
'''

(SRC / 'prototype.html').write_text(out)
print('wrote', SRC / 'prototype.html', len(out), 'bytes')
